### PR TITLE
Merge search distance matrix to master

### PR DESCRIPTION
**Pull request by Sahadporn**
Update:
- Add search features with distance matrix.
- Add more descriptions to map ui in condo page.
- Delete P.A.I.M.O.N. block in condo page.
- Change admin url.
- Delete image card overlay changed it to hover.

Please check and approve my code. Thanks.

### CODE REVIEW

**Comment by ZEZAY** [comment]
I think you should remove some import that never been use too, like on the urls,
And I think may be models/transit_data should move to static, no?

**Comment by GifperTC** [comment]
I'm resolving conflicts right now, most of the one I did was the refactoring one, but there are some conflicts that I'm not very sure. If someone still available please confirm my messages sent in LINE.

**Comment by GifperTC** [comment]
All conflicts resolved, code looks fine to me.

**Comment by GifperTC** [comment]
If Chanathip come and recheck the code, please merge this pull request.

**Pull request merged**
