### PR TITLE
Merge custom user to Iteration2

### PR DESCRIPTION
**Pull request by phuwanutj**
This branch aims to create an authentication for the `Owner` model.
Right now, it fails to migrate.
Please help me to solve this issue.
I also encountered an exception value `no such table: estate_customuser`

### CODE REVIEW

**Comment by Sahadporn** [comment]
I encountered the same problem yesterday.
Have you tried delete the db.sqlite file, all files in migrations except __init__  before makemigrations yet?

**Comment by phuwanutj** [comment]
I just got the custom user to work, but no oauth yet.

**Comment by kaesrel** [comment]
I can sign up and login, but I could not create any superuser.

**Comment by kaesrel** [comment]
Okay, it has been fixed and I can now create superuser.

**Comment by Sahadporn** [comment]
The code looks good to me.

**Review by kaesrel — APPROVED** [review]
I already reviewed before this request. It works fine.

**Comment by phuwanutj** [comment]
Thank you. I will merge them into iteration02 now.

**Pull request merged**
